- name: Switch apache2 configs
  copy:
      src: '{{apache2_home}}/conf/httpd.conf.jboss'
      dest: '{{apache2_home}}/httpd.conf'

- name: Reload service httpd, in all cases
  service:
      name: apache
      state: restarted
