---
- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: add group {{os_group}}
  group: name={{os_group}}

- name: add user {{os_username}}
  user: name={{os_username}} group={{os_group}} home=/usr/share/{{os_username}} createhome=yes
  become: yes
  become_method: sudo

- name: Create directories for Tomcat
  file:
      path: /opt/software
      state: directory
      recurse: yes
      mode: 0775

- name: Download Tomcat 8.5.43
  get_url:
      url: http://mirror.linux-ia64.org/apache/tomcat/tomcat-8/v8.5.43/bin/apache-tomcat-8.5.43.zip
      dest: /tmp/

- name: Extract archive
  unarchive:
      src: /tmp/apache-tomcat-8.5.43.zip
      dest: /opt/software/

- name: Remove archive after processed
  file:
      path: /tmp/apache-tomcat-8.5.43.zip
      state: absent

- name: set {{os_username}} user as owner
  file:
      path: "{{item}}"
      state: directory
      owner: {{os_username}}
      group: {{os_group}}
      recurse: yes
  with_items:
      - /opt/software
      - /opt/software/apache-tomcat-8.5.43

- name: Symlink install directory
  file:
      src: /opt/software/apache-tomcat-8.5.43
      path: /usr/share/tomcat
      state: link

- name: Configure Tomcat server
  template:
      src: server.xml
      dest: /usr/share/tomcat/conf/
#  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-init.sh dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port={{http_port}}
